aomdc22.wad
gfx/env/sorgardbk.tga
gfx/env/sorgarddn.tga
gfx/env/sorgardft.tga
gfx/env/sorgardlf.tga
gfx/env/sorgardrt.tga
gfx/env/sorgardup.tga
models/aomdc/props/farmor.mdl
models/aomdc/sick/doctor1.mdl
models/aomdc/sick/doctor2.mdl
models/aomdc/sick/doctor3.mdl
models/aomdc/sick/player45.mdl
sound/aomdc/ambience/sheller.wav
sound/aomdc/musics/4endsong45.wav
sound/aomdc/musics/creditnote.wav
sound/aomdc/musics/credits.wav
sound/aomdc/saker/ekg_alive.wav
sound/aomdc/saker/ekg_dead.wav
sprites/aomdc/zcredits.spr
sprites/aomdc/640_wep1.spr
sprites/aomdc/640_wep2.spr
sprites/aomdc/640_wep3.spr
sprites/aomdc/640_wep4.spr
sprites/aomdc/640_wep5.spr
sprites/aomdc/640_wep6.spr
sprites/aom_weapons/weapon_aomglock.txt
sprites/aom_weapons/weapon_aomshotgun.txt
sprites/aom_weapons/weapon_aomuzi.txt
sprites/aom_weapons/weapon_axe.txt
sprites/aom_weapons/weapon_beretta.txt
sprites/aom_weapons/weapon_deagle.txt
sprites/aom_weapons/weapon_gmgeneral.txt
sprites/aom_weapons/weapon_hammer.txt
sprites/aom_weapons/weapon_knife.txt
sprites/aom_weapons/weapon_mp5k.txt
sprites/aom_weapons/weapon_p228.txt
sprites/aom_weapons/weapon_revolver.txt
sprites/aom_weapons/weapon_revolver_golden.txt
sprites/aom_weapons/weapon_spear.txt
models/player/david/david.mdl
models/player/david/david.bmp
models/player/davidbad/davidbad.mdl
models/player/davidbad/davidbad.bmp
models/player/davidd/davidd.mdl
models/player/davidd/davidd.bmp