aomdc22.wad
models/aomdc/cutscene/e2_david.mdl
models/aomdc/props/datastol2.mdl
models/aomdc/sick/question.mdl
sound/aomdc/ambience/boomer.wav
sound/aomdc/ambience/spooky_wind_apartment.wav
sound/aomdc/musics/creditnote.wav
sound/aomdc/musics/credits.wav
sprites/aomdc/zcredits.spr
sprites/aomdc/640_wep1.spr
sprites/aomdc/640_wep2.spr
sprites/aomdc/640_wep3.spr
sprites/aomdc/640_wep4.spr
sprites/aomdc/640_wep5.spr
sprites/aomdc/640_wep6.spr
sprites/aom_weapons/weapon_aomglock.txt
sprites/aom_weapons/weapon_aomshotgun.txt
sprites/aom_weapons/weapon_aomuzi.txt
sprites/aom_weapons/weapon_axe.txt
sprites/aom_weapons/weapon_beretta.txt
sprites/aom_weapons/weapon_deagle.txt
sprites/aom_weapons/weapon_gmgeneral.txt
sprites/aom_weapons/weapon_hammer.txt
sprites/aom_weapons/weapon_knife.txt
sprites/aom_weapons/weapon_mp5k.txt
sprites/aom_weapons/weapon_p228.txt
sprites/aom_weapons/weapon_revolver.txt
sprites/aom_weapons/weapon_revolver_golden.txt
sprites/aom_weapons/weapon_spear.txt
models/player/david/david.mdl
models/player/david/david.bmp
models/player/davidbad/davidbad.mdl
models/player/davidbad/davidbad.bmp
models/player/davidd/davidd.mdl
models/player/davidd/davidd.bmp