aomdc22.wad
gfx/env/darkcitybk.tga
gfx/env/darkcitydn.tga
gfx/env/darkcityft.tga
gfx/env/darkcitylf.tga
gfx/env/darkcityrt.tga
gfx/env/darkcityup.tga
models/aomdc/monsters/devourer/devourer.mdl
models/aomdc/monsters/face/face_new.mdl
models/aomdc/monsters/twitcher/twitcher.mdl
models/aomdc/monsters/twitcher/twitcher3.mdl
models/aomdc/monsters/twitcher/twitcher4.mdl
models/aomdc/weapons/beretta/p_beretta.mdl
models/aomdc/weapons/beretta/v_beretta.mdl
models/aomdc/weapons/beretta/w_beretta.mdl
models/aomdc/weapons/deagle/p_deagle.mdl
models/aomdc/weapons/deagle/v_deagle.mdl
models/aomdc/weapons/deagle/w_deagle.mdl
models/aomdc/weapons/glock/p_glock.mdl
models/aomdc/weapons/glock/v_glock.mdl
models/aomdc/weapons/glock/w_glock.mdl
models/aomdc/weapons/hammer/p_hammer.mdl
models/aomdc/weapons/hammer/v_hammer.mdl
models/aomdc/weapons/hammer/w_hammer.mdl
models/aomdc/weapons/knife/p_knife.mdl
models/aomdc/weapons/knife/v_knife.mdl
models/aomdc/weapons/knife/w_knife.mdl
models/aomdc/weapons/mp5k/p_mp5k.mdl
models/aomdc/weapons/mp5k/v_mp5k.mdl
models/aomdc/weapons/mp5k/w_mp5k.mdl
models/aomdc/weapons/p228/p_p228.mdl
models/aomdc/weapons/p228/v_p228.mdl
models/aomdc/weapons/p228/w_p228.mdl
models/aomdc/weapons/shotgun/p_shotgun.mdl
models/aomdc/weapons/shotgun/v_shotgun.mdl
models/aomdc/weapons/shotgun/w_shotgun.mdl
models/aomdc/weapons/uzi/p_uzi.mdl
models/aomdc/weapons/uzi/v_uzi.mdl
models/aomdc/weapons/uzi/w_uzi.mdl
sound/aomdc/ambience/drips.wav
sound/aomdc/ambience/sparks.wav
sound/aomdc/aompa/sickfromsick.wav
sound/aomdc/player/breathe1.wav
sprites/aomdc/fog5.spr
sprites/aomdc/levelchange.spr
sprites/aomdc/moths.spr
sprites/aomdc/640_wep1.spr
sprites/aomdc/640_wep2.spr
sprites/aomdc/640_wep3.spr
sprites/aomdc/640_wep4.spr
sprites/aomdc/640_wep5.spr
sprites/aomdc/640_wep6.spr
sprites/aom_weapons/weapon_aomglock.txt
sprites/aom_weapons/weapon_aomshotgun.txt
sprites/aom_weapons/weapon_aomuzi.txt
sprites/aom_weapons/weapon_axe.txt
sprites/aom_weapons/weapon_beretta.txt
sprites/aom_weapons/weapon_deagle.txt
sprites/aom_weapons/weapon_gmgeneral.txt
sprites/aom_weapons/weapon_hammer.txt
sprites/aom_weapons/weapon_knife.txt
sprites/aom_weapons/weapon_mp5k.txt
sprites/aom_weapons/weapon_p228.txt
sprites/aom_weapons/weapon_revolver.txt
sprites/aom_weapons/weapon_revolver_golden.txt
sprites/aom_weapons/weapon_spear.txt
models/player/david/david.mdl
models/player/david/david.bmp
models/player/davidbad/davidbad.mdl
models/player/davidbad/davidbad.bmp
models/player/davidd/davidd.mdl
models/player/davidd/davidd.bmp