gfx/env/hangingstone256_bk.tga
gfx/env/hangingstone256_dn.tga
gfx/env/hangingstone256_ft.tga
gfx/env/hangingstone256_lf.tga
gfx/env/hangingstone256_rt.tga
gfx/env/hangingstone256_up.tga
models/inv_xmas/helmet.mdl
models/inv_xmas/pine.mdl
models/inv_xmas/pyro.mdl
models/inv_xmas/sgmachine01.mdl
models/inv_xmas/sgmachine.mdl
models/inv_xmas/sgmachinet.mdl
models/inv_xmas/snowbot.mdl
models/inv_xmas/snowbot01.mdl
models/inv_xmas/snowbot02.mdl
models/inv_xmas/snowgarg.mdl
models/inv_xmas/snowgargt.mdl
models/inv_xmas/snowman.mdl
models/inv_xmas/snowmant.mdl
models/inv_xmas/snowmonster.mdl
sound/inv_xmas/sw_blazwar1.wav
maps/inv_frozen.cfg
maps/inv_frozen.res
maps/inv_frozen_skl.cfg